name: 'Terraform'

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  id-token: write
  contents: read
  pull-requests: write

env:
  ARM_USE_OIDC: true
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  # ARM_USE_AZUREAD: true
  TF_CLI_ARGS_plan: "-lock-timeout=5m"
  TF_CLI_ARGS_apply: "-lock-timeout=5m"
  TF_WORKSPACE: "dev"

jobs:
  terraform:
    name: 'Terraform'
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    environment: dev

    defaults:
      run:
        shell: bash

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Azure OIDC Login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        enable-AzPSSession: true
    
    # Run az commands to confirm sub access
    - name: Azure CLI script
      uses: azure/cli@v2
      with:
        azcliversion: latest
        inlineScript: |
          az account show

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      env:
        ARM_USE_AZUREAD: true
        ARM_USE_OIDC: true      
      with:
        terraform_version: "1.7.0"
        terraform_wrapper: false

    - name: Terraform Format
      id: fmt
      run: terraform fmt -check -recursive
      continue-on-error: true

    - name: Terraform Init
      id: init
      run: |
        for i in {1..3}; do
          terraform init && break
          if [ $i -eq 3 ]; then
            echo "Failed to initialize after 3 attempts"
            exit 1
          fi
          echo "Retrying initialization in 30 seconds..."
          sleep 30
        done
      working-directory: environments/${{ env.TF_WORKSPACE }}

    - name: Terraform Validate
      id: validate
      run: terraform validate
      working-directory: environments/${{ env.TF_WORKSPACE }}

    - name: Terraform Plan
      id: plan
      if: github.event_name == 'pull_request'
      run: |
        for i in {1..3}; do
          terraform plan -no-color && break
          if [ $i -eq 3 ]; then
            echo "Failed to plan after 3 attempts"
            exit 1
          fi
          echo "Retrying plan in 30 seconds..."
          sleep 30
        done
      working-directory: environments/${{ env.TF_WORKSPACE }}
      continue-on-error: true

    - name: Update Pull Request
      uses: actions/github-script@v7
      if: github.event_name == 'pull_request'
      env:
        PLAN: "${{ steps.plan.outputs.stdout }}"
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
          #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
          #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
          #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
          
          <details><summary>Show Plan</summary>
          
          \`\`\`\n
          ${process.env.PLAN}
          \`\`\`
          
          </details>`;
          
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: output
          })

    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: |
        for i in {1..3}; do
          terraform apply -auto-approve && break
          if [ $i -eq 3 ]; then
            echo "Failed to apply after 3 attempts"
            exit 1
          fi
          echo "Retrying apply in 30 seconds..."
          sleep 30
        done
      working-directory: environments/${{ env.TF_WORKSPACE }} 